# Generated by Django 5.1b1 on 2026-03-19 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tandarunner", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainingInsight",
        ),
    ]
