# Generated by Django 5.1b1 on 2026-03-22 15:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tandarunner", "0002_delete_traininginsight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("goal", models.TextField()),
                ("coach_message", models.TextField(blank=True, default="")),
                ("goal_date", models.DateField(blank=True, null=True)),
                ("sessions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
