# Generated by Django 5.1b1 on 2026-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tandarunner", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="achievability",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
