# Generated by Django 5.1b1 on 2026-03-22 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tandarunner", "0004_trainingplan_achievability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingplan",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="trainingplan",
            name="goal_date",
        ),
    ]
